version: '3.5'
services:
  app:
    image: ghcr.io/dsbykov/alpina_bot_builder:latest
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    healthcheck:  # проверка готовности приложения
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Передаём переменные окружения для Django
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}  # из .env или окружения
      # Указываем параметры БД (должны совпадать с settings.py)
      DB_NAME: $(DB_NAME)
      DB_USER: $(DB_USER)
      DB_PASSWORD: $(DB_PASSWORD)
      DB_HOST: $(DB_HOST)                   # имя сервиса в Docker-сети
      DB_PORT: $(DB_PORT)
    # Монтируем .env, если используете
    # volumes:
    #   - ./.env:/app/.env          # путь к .env внутри контейнера

  db:
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    volumes:
      - app-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $(DB_NAME)
      POSTGRES_USER: $(DB_USER)
      POSTGRES_PASSWORD: $(DB_PASSWORD)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  app-postgres:
    driver: bridge
    