services:
  app:
    image: ghcr.io/dsbykov/alpina_bot_builder:latest
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - GIGACHAT_AUTH_KEY=${GIGACHAT_AUTH_KEY}
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./logs:/app/logs
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    volumes:
      - "db:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: bot_builder_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", $$POSTGRES_DB, "-U", $$POSTGRES_USER ]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 30s

  bot:
    image: ghcr.io/dsbykov/alpina_bot_builder:latest
    build:
      context: .
    command: python bot_runner.py
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - /var/www/certbot:/var/www/certbot:ro
      - /etc/letsencrypt/live/my-bot-builder.ru/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/my-bot-builder.ru/privkey.pem:/etc/nginx/ssl/privkey.pem
volumes:
  db:
  static_volume:
  media_volume:
