# Generated by Django 5.2.7 on 2025-11-25 10:52

import django.db.models.deletion
from django.db import migrations, models


def fix_invalid_foreignkeys(apps, schema_editor):
    # Получаем модель через apps (чтобы избежать проблем с импортом)
    # замените your_app_name на имя вашего приложения
    Step = apps.get_model('api', 'Step')

    # Находим все записи с некорректными ссылками
    invalid_records = Step.objects.filter(next_step_id__isnull=False).exclude(
        next_step_id__in=Step.objects.values_list('id', flat=True)
    )

    # Устанавливаем NULL для некорректных ссылок
    invalid_records.update(next_step_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fix_invalid_foreignkeys),
        migrations.AlterField(
            model_name='step',
            name='next_step_id',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.step'),
        ),
    ]
