# Generated by Django 5.2.7 on 2026-03-30 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_scenario_options_alter_step_options_bot_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='api.bot'),
        ),
    ]
