# Generated by Django 5.2.7 on 2025-11-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_scenario_is_active_bot_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
