# Generated by Django 5.2.7 on 2026-04-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_scenario_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
