# Generated by Django 5.2.7 on 2025-11-05 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bot_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('current_step_id', models.IntegerField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bot')),
            ],
            options={
                'unique_together': {('user_id', 'bot')},
            },
        ),
    ]
